Fix indentation and formatting in sensor.py
Was getting an error in HA, which was caused by bad indentation.
Corrected and now integration loads up correctly

File "/config/custom_components/power_load_balancer/sensor.py", line 115 self._attr_extra_state_attributes["events"].append(log_entry)
IndentationError: unexpected indent